# Generated by Django 4.1.7 on 2024-03-07 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('poster', models.ImageField(null=True, upload_to='poster')),
                ('release_date', models.DateField(null=True)),
                ('description', models.TextField(blank=True)),
                ('actors', models.CharField(max_length=250, null=True)),
                ('trailer_link', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.category')),
            ],
        ),
    ]
